### ISSUE TITLE
Schemes and other bits for module 4xTMC2208 for AIO II board

### ISSUE THREAD

**Issue by sl1pkn07** [FYSETC/AIO_II#3]
Hi

i just discover exist a module for this board with TMC2208 drivers

https://es.aliexpress.com/item/4000337065284.htm

is possible add to the repo the schemes/layout/otherbits to the repo?

greetings

**Comment by Cadaxe20000** [comment]
I have ordered one with 2208 and I can't find anywhere how to resolve compailing issues for 2208 pins

**Comment by sl1pkn07** [comment]
unit received today

any notice of the schemes and push the marlin configuratin for this drivers in upstream?

greetings

**Comment by Cadaxe20000** [comment]
No, I did asks manufacturer few times and usually they reply everything is
included on GitHub.

**Comment by sl1pkn07** [comment]
practically almost 2 years later, but now done

tnx!
