### ISSUE TITLE
Unable to use P4 serial port pinheader

### ISSUE THREAD

**Issue by sl1pkn07** [FYSETC/AIO_II#7]
related

https://github.com/FYSETC/Marlin-2.0.x-FYSETC/issues/21

greetings

**Comment by TuguanLing** [comment]
Hello, I tested according to your configuration, it can be received and sent normally, you should be connected to the wrong line, USART2_TX and USART2_RX are PA2 and PA3 respectively. In addition, USART2 has been used in TMC2208's uart mode. Although it can receive and send instructions, it also receives instructions from TMC2208's uart mode. It is recommended not to use USART2.

**Comment by sl1pkn07** [comment]
Hi

then, i can't use P4 port if use the 4xTMC2208 module? then what happen if use the the P6 header (pin header near the USB port)? is usart1 (througth CH340 bridge). the usb is irrelevant for me (only when i need flash the firmware)

greetings

**Comment by TuguanLing** [comment]
If you use USART1, you do not need to turn on SERIAL_PORT_2,USB to send instructions and burn firmware, but the P6 interface cannot be directly used for WiFi modules to send instructions. USART1_TX and USART1_RX need to be extracted from MCU. Check the schematic diagram in detail

**Comment by sl1pkn07** [comment]
according to STM32F103RCT6 datasheet (https://www.st.com/resource/en/datasheet/stm32f103rc.pdf) this Mcu, also have USART3, wich in AIOII schemes, is also in the P4 header, the low row (PB10 (SCL) and PB11 (SCA))

but this connection, have 2 resistors (4,7K). exist any problem if i use as serial port as-sis? or i need retire the resistors?

greetings

**Comment by TuguanLing** [comment]
USART3 can be used normally, no need to retire the resistors, does not affect the normal use.

**Comment by sl1pkn07** [comment]
thanks for confirm . i have tested in my 2 units and works ok in USART3 (`SERIAL_PORT_2 3`)(P4 upper row pin) when use 4xTMC2208 module, and  USART2 (`SERIAL_PORT_2 2`)(P4 lower row pin) and USART3 (`SERIAL_PORT_2 3`) when use 4xST820 module

greetings

PD: is cross-related with https://github.com/FYSETC/FYSETC-AIO_II/issues/3. 4xTMC2208 module schemes and other bits is missing in the repository
